add roll commands
AgentRBY/HL_Bot pull request #7
Opened 2023-04-06 17:50 UTC by ilfey

2023-04-06 17:56 UTC, bot08 commented on src/commands/Common/Utils/RollCommand.ts
> +          InfoEmbed('Я достигла комедии. Минимальное число не может быть больше максимального или равняться ему')
Предлагаю не делать 1000-7

2023-04-06 17:57 UTC, ilfey commented on src/commands/Common/Utils/RollCommand.ts
> +          InfoEmbed('Я достигла комедии. Минимальное число не может быть больше максимального или равняться ему')
I have achieved Comedy

2023-04-06 17:57 UTC, ilfey commented on src/commands/Slash/Utils/RollCommand.ts
> +          InfoEmbed('Я достигла комедии. Минимальное число не может быть больше максимального или равняться ему')
I have achieved Comedy

2023-04-06 18:03 UTC, ilfey commented on src/commands/Common/Utils/RollCommand.ts
> +          InfoEmbed('Я достигла комедии. Минимальное число не может быть больше максимального или равняться ему')
Тогда диапазон будет выглядеть вот так: `[0;100]` и не включать **100**, хотя по нотации **[]** <- включая значения или `(0;100)` **()** <- не включая, но при этом **0** включается

> Предлагаю не делать 1000-7

2023-04-06 18:19 UTC, bot08 approved these changes

2023-04-06 18:35 UTC, bot08 requested changes

2023-04-06 18:35 UTC, bot08 commented on src/commands/Common/Utils/RollCommand.ts
> +        embeds: [
Комментарии излишни
![image](https://user-images.githubusercontent.com/71845954/230463726-eb2c3b91-84d8-44ec-b927-18b74b3b1fd7.png)

2023-04-08 06:32 UTC, AgentRBY requested changes

2023-04-08 06:32 UTC, AgentRBY commented on src/commands/Common/Utils/RollCommand.ts
> +    message.sendSuccess(`Ваше случайное число [0;${max}] - \`${Math.floor(Math.random() * (max + 1))}\``);
Вынеси число в отдельную переменную. Плюс можно использовать `getRandomInt()` из `/src/utils/Common/Number.ts`

2023-04-08 06:32 UTC, AgentRBY commented on src/commands/Slash/Utils/RollCommand.ts
> +        fetchReply: true,
Не нужно фетчить reply, если ты не используешь его

2023-04-08 06:32 UTC, AgentRBY commented on src/commands/Slash/Utils/RollCommand.ts
> +      let randomIntegerString = Math.floor(Math.random() * 10 ** 16).toString();
Давай переименуем в просто randomInteger

2023-04-08 07:17 UTC, merged